### ISSUE TITLE
Compatible with text editor?

### ISSUE THREAD

**Issue by Alexey-T** [terrylao/FPC_PATCH#1]
I am not good in Macs, and I also don't have CJK IME on my Mac, so I cannot test.
Can somebody test the CudaText (or just ATSynEdit demo) - is it working better with the patch? CJK IME is working now?

@jairomartinezA / @veksha / @rasberryrabbit is maybe interested.

https://github.com/alexey-t/atsynedit
demo in the app/demo_editor folder.

**Comment by JairoMartinezA** [comment]
Hi Alex,

But what you want to test specifically? CJK chars?

**Comment by Alexey-T** [comment]
Jairo

- first you need to install CJK (e.g. Japanese) IME on your Mac
- then apply patches to your Lazarus
- then rebuild the IDE: in IDE - "Tools / Configure build lazarus",  check "Clean all"

![Screenshot_2022-10-10_19-46-54](https://user-images.githubusercontent.com/4154978/194915732-2afd1d09-7276-47a5-bf69-fe72c27dc719.png)

- then rebuild ATSynEdit demo and test Japanese input

**Comment by Alexey-T** [comment]
@JairoMartinezA Wait, don't work yet, patch is changing every day. let's wait some days.

**Comment by terrylao** [comment]
Alexey,
  maybe you can have a test.

**Comment by Alexey-T** [comment]
@terrylao It's pain for me to turn on my old Mac. it's slooow.

**Comment by JairoMartinezA** [comment]
@terrylao what is the test? just write something?

**Comment by Alexey-T** [comment]
I wanted that somebody compiles ATSynEdit demo_editor, and tests Japanese/Chinese IME inputs there.

**Comment by JairoMartinezA** [comment]
I am right now updating FPC and Lazarus. I will try your steps above in a few minutes.

**Comment by Alexey-T** [comment]
Jairo, wait few days, TerryLao changes patches for Laz every day.

**Comment by terrylao** [comment]
I had closed my issue already. It should be ok now.

**Comment by Alexey-T** [comment]
Jairo, see progress of patches
https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39899

**Comment by JairoMartinezA** [comment]
The update process has finished:
![image](https://user-images.githubusercontent.com/5806694/195215118-dd5d0c78-8c3d-459d-9c7f-5824454432a6.png)

Then the question, wait or not to wait.

**Comment by Alexey-T** [comment]
wait.

**Comment by terrylao** [comment]
fix on windows and macOS was done
